<?php

namespace FinanceTracker\Infrastructure\Domain\Entities\Hydradors;

use Doctrine\ODM\MongoDB\DocumentManager;
use Doctrine\ODM\MongoDB\Mapping\ClassMetadata;
use Doctrine\ODM\MongoDB\Hydrator\HydratorInterface;
use Doctrine\ODM\MongoDB\UnitOfWork;

/**
 * THIS CLASS WAS GENERATED BY THE DOCTRINE ODM. DO NOT EDIT THIS FILE.
 */
class FinanceTrackerDomainEntitiesTagHydrator implements HydratorInterface
{
    private $dm;
    private $unitOfWork;
    private $class;

    public function __construct(DocumentManager $dm, UnitOfWork $uow, ClassMetadata $class)
    {
        $this->dm = $dm;
        $this->unitOfWork = $uow;
        $this->class = $class;
    }

    public function hydrate($document, $data, array $hints = array())
    {
        $hydratedData = array();

        /** @Field(type="id") */
        if (isset($data['_id'])) {
            $value = $data['_id'];
            $return = $value instanceof \MongoId ? (string) $value : $value;
            $this->class->reflFields['_tagId']->setValue($document, $return);
            $hydratedData['_tagId'] = $return;
        }

        /** @Field(type="string") */
        if (isset($data['_name'])) {
            $value = $data['_name'];
            $return = (string) $value;
            $this->class->reflFields['_name']->setValue($document, $return);
            $hydratedData['_name'] = $return;
        }

        /** @Many */
        $mongoData = isset($data['_transactions']) ? $data['_transactions'] : null;
        $return = new \Doctrine\ODM\MongoDB\PersistentCollection(new \Doctrine\Common\Collections\ArrayCollection(), $this->dm, $this->unitOfWork, '$');
        $return->setHints($hints);
        $return->setOwner($document, $this->class->fieldMappings['_transactions']);
        $return->setInitialized(false);
        if ($mongoData) {
            $return->setMongoData($mongoData);
        }
        $this->class->reflFields['_transactions']->setValue($document, $return);
        $hydratedData['_transactions'] = $return;
        return $hydratedData;
    }
}